# Generated by Django 4.2 on 2023-04-14 18:42

from django.db import migrations

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TasksStatus = apps.get_model('backend_api', 'TasksStatus')
    for status in ['new', 'in_work', 'done']:
        new_status = TasksStatus(status=status)
        new_status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
    ]
